
name: First Workflow - refactor
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print output
      - run: |
            echo "Hello World!"
            echo "Donezo!"
